import Link from "next/link";
import { ArrowRight, Mail, MessageCircle } from "lucide-react";
import { investmentPlans, investmentSteps, legacyExplanation } from "@/features/content/legacy-content";

export function WelcomePanel() {
  return <section id="home" className="shell grid min-h-[38rem] items-center gap-10 py-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow">Great finance</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[1.03] tracking-[-.05em] text-balance sm:text-7xl">Exceed your financial struggles today with <span className="text-[var(--brand)]">Great finance</span> and make your future easier.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted)]">Register as a customer or vendor, use verified payment channels, and follow every financial action through a secure, role-based dashboard.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="rounded-xl bg-[var(--brand)] px-5 py-3 font-bold text-white" href="/login">Login</Link><Link className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-5 py-3 font-bold text-[var(--surface-inverse)]" href="/signup">Register <ArrowRight size={18}/></Link></div></div><div className="relative min-h-80 overflow-hidden rounded-[2rem] bg-[var(--surface-inverse)] p-8 text-white shadow-[0_30px_80px_rgb(0_0_0_/_24%)]"><div className="absolute -right-20 -top-20 size-64 rounded-full bg-[var(--brand)]/30 blur-2xl"/><p className="relative text-sm text-white/60">Built for accountable operations</p><p className="relative mt-28 max-w-sm text-3xl font-semibold tracking-[-.03em]">Customer, vendor and administrator workflows—connected by verified records.</p></div></section>;
}

export function Explanation() {
  return <section id="about" className="bg-[var(--surface-inverse)] py-20 text-white"><div className="shell grid gap-8 lg:grid-cols-[.45fr_1fr]"><div><p className="text-sm font-bold text-[var(--accent)]">About Great Finance</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.035em]">A clearer path through every financial action.</h2></div><p className="max-w-3xl text-lg leading-8 text-white/70">{legacyExplanation}</p></div></section>;
}

export function HowToInvest() {
  return <section className="shell py-24"><p className="eyebrow">Process</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.035em]">How To Invest</h2><ol className="mt-12 grid gap-px overflow-hidden rounded-[1.5rem] bg-[var(--line)] md:grid-cols-2">{investmentSteps.map((guide, index) => <li className="min-h-48 bg-[var(--surface)] p-7" key={guide}><span className="font-mono text-3xl text-[var(--brand)]">0{index + 1}</span><p className="mt-8 max-w-md text-lg leading-7 first-letter:uppercase">{guide}</p></li>)}</ol></section>;
}

export function OurPlans() {
  return <section id="plans" className="bg-[var(--surface-muted)] py-24"><div className="shell"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Catalogue</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.035em]">Our Plans</h2></div><p className="max-w-md text-sm leading-6 text-[var(--muted)]">Plan activation and financial postings require verified payment and administrative approval.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{investmentPlans.map((plan, index) => <article className={`flex min-h-64 flex-col rounded-[1.35rem] p-6 ${index === 3 ? "bg-[var(--brand)] text-white" : "bg-white"}`} key={plan.name}><p className={`text-xs font-bold tracking-[.12em] ${index === 3 ? "text-[#ffdc87]" : "text-[var(--brand)]"}`}>{plan.name}</p><div className="mt-7 flex items-end gap-3"><span className="text-3xl font-semibold tabular-nums">${plan.amount.toLocaleString("en-US")}</span><span className={index === 3 ? "text-white/70" : "text-[var(--muted)]"}>to get</span></div><p className="mt-2 text-2xl font-semibold tabular-nums">${plan.returnAmount.toLocaleString("en-US")}</p><div className={`mt-auto flex items-center justify-between border-t pt-5 ${index === 3 ? "border-white/25" : "border-[var(--line)]"}`}><span className="text-sm">R.O.I · {plan.duration} days</span><Link className={`font-bold ${index === 3 ? "text-[#ffdc87]" : "text-[var(--brand)]"}`} href="/dashboard/investment">Invest</Link></div></article>)}</div></div></section>;
}

export function ContactUs() {
  return <section id="contact" className="shell py-24"><p className="eyebrow">Support</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.035em]">Contact Us</h2><div className="mt-10 grid gap-4 md:grid-cols-2"><a className="flex items-center gap-5 rounded-2xl bg-white p-6 shadow-[0_18px_45px_rgba(16,37,63,.08)]" href="mailto:greatfinanceng@gmail.com"><Mail className="text-[var(--brand)]"/><span><span className="block text-sm text-[var(--muted)]">Send us an email</span><strong>greatfinanceng@gmail.com</strong></span></a><a className="flex items-center gap-5 rounded-2xl bg-white p-6 shadow-[0_18px_45px_rgba(16,37,63,.08)]" href="https://wa.me/2347031069524"><MessageCircle className="text-[var(--brand)]"/><span><span className="block text-sm text-[var(--muted)]">Chat with us on WhatsApp</span><strong>07031069524</strong></span></a></div></section>;
}

export function SiteFooter() {
  return <footer className="border-t border-[var(--line)] bg-white py-8"><div className="shell flex flex-wrap items-center justify-between gap-4 text-sm text-[var(--muted)]"><span>Copyright © <strong className="text-[var(--ink)]">greatfinance.com. All Rights Reserved.</strong></span><span className="flex gap-5"><Link href="/#about">About Great Finance</Link><Link href="/#contact">Contact</Link></span></div></footer>;
}
